In [1]:
# analyze /allah/freqtrade/user_data/data/binance/BTC_USDT_USDT-1m.feather as dataframe
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# df = pd.read_feather('/allah/freqtrade/user_data/data/binance/BTC_USDT_USDT-1m.feather')

In [4]:
# analyze /allah/freqtrade/user_data/data/binance/BTC_USDT_USDT-trades.feather as dataframe
# df_t = pd.read_feather('/allah/freqtrade/user_data/data/binance/BTC_USDT_USDT-trades.feather')
input_path = '/allah/freqtrade/user_data/data/binance/futures/BTC_USDT_USDT-1s-futures.feather'

In [7]:
df_t

          timestamp          id  type  side    price  amount       cost
0     1698624000036  1898897182  None   buy  34528.6   0.001    34.5286
1     1698624000059  1898897183  None  sell  34528.5   0.150  5179.2750
2     1698624004893  1898897184  None   buy  34528.6   0.060  2071.7160
3     1698624004901  1898897185  None  sell  34528.5   0.010   345.2850
4     1698624004903  1898897186  None   buy  34528.6   0.007   241.7002
...             ...         ...   ...   ...      ...     ...        ...
4990  1698624604343  1898902172  None  sell  34563.1   0.009   311.0679
4991  1698624604965  1898902173  None   buy  34563.2   0.072  2488.5504
4992  1698624606264  1898902174  None   buy  34563.2   0.061  2108.3552
4993  1698624607044  1898902175  None   buy  34563.2   0.002    69.1264
4994  1698624607677  1898902176  None   buy  34563.2   0.005   172.8160

[4995 rows x 7 columns]

In [8]:
df

                        date     open     high      low    close   volume
0  2023-10-30 00:00:00+00:00  34528.6  34550.4  34528.5  34549.8  131.351
1  2023-10-30 00:01:00+00:00  34549.9  34552.9  34532.6  34547.3  124.704
2  2023-10-30 00:02:00+00:00  34547.2  34559.6  34542.8  34558.9  141.939
3  2023-10-30 00:03:00+00:00  34558.8  34570.6  34557.0  34562.9  195.096
4  2023-10-30 00:04:00+00:00  34562.8  34570.6  34549.8  34553.4  152.279
5  2023-10-30 00:05:00+00:00  34553.4  34562.7  34552.8  34553.0   55.435
6  2023-10-30 00:06:00+00:00  34552.9  34567.1  34548.0  34567.1   58.772
7  2023-10-30 00:07:00+00:00  34567.0  34577.1  34567.0  34577.1   90.061
8  2023-10-30 00:08:00+00:00  34577.0  34577.4  34571.3  34571.4   50.521
9  2023-10-30 00:09:00+00:00  34571.3  34578.8  34563.1  34563.1   99.818
10 2023-10-30 00:10:00+00:00  34563.2  34563.2  34563.1  34563.2    0.340